services:
  postgres:
    image: postgres:12-alpine
    container_name: db-postgres-aula_system
    environment:
      - POSTGRES_DB=aula_system
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    networks:
      - netms1
networks:
  netms1:
    name: net-ms1

#  sudo docker-compose up -d