server:
  port: 8080
  servlet:
    context-path: /aula-system
#  port: ${PORT:0} // para puerto aleatorio
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/aulasystem
    username: postgres
    password: aulasystem
  jpa:
      hibernate:
         ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show_sql: true
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:backend
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        '[show_sql]': true
#        '[use_sql_comments]': false
#        '[format_sql]': true
#    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
configuration:
  reactHost: http://localhost:3000
