server:
  port: 8080
#  port: ${PORT:0}
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: backend
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:backend
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': true
    show-sql: true